name: deeplink_sdk
description: A complete SDK for deferred deep linking, attribution, and smart routing.
version: 0.0.1
homepage: https://deeplink.invyto.in
repository: https://github.com/prashobkanhangad/deeplink_pkg

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0
  app_links: ^6.3.0
  url_launcher: ^6.2.0
  device_info_plus: ^10.1.0
  android_play_install_referrer: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
